### ISSUE TITLE
How to make this work if using <datalist>

### ISSUE THREAD

**Issue by jazzu20** [marvicrm/ph_provinces_and_cities#3]
The cities don't populate. how can we make this work using datalist?

```
<input required class="required" list="province" name="attributes[Province]" value="" placeholder="Select Province" />
<datalist id="province"></datalist>

<input required class="required" list="city" name="attributes[City]" value="" placeholder="Select City/Municipality" />
<datalist id="city"></datalist>
```

**Comment by marvicrm** [comment]
Oh sorry for the very very very late reply haha. 

Here is a sample code :) 

`<html>
<head>
<script src="https://www.marvicrm.com/scripts/ph_provinces_and_cities/city.js"></script>
</head>
<body>

<input onchange="select_city(this)" list="provinces" name="province">
<datalist id="provinces"></datalist>

<input list="cities" name="city">
<datalist id="cities"></datalist>
  
<script>
	
	var $ = new City();
	for(var province in cities) {
		document.querySelector( 'datalist#provinces' ).innerHTML += '<option>' + province + '</option>';
	}
	
	function select_city( e ) {
		for(var city in $.getCities( e.value ) ) {
			document.querySelector( 'datalist#cities' ).innerHTML += '<option>' + $.getCities( e.value )[city] + '</option>';
		}
	}
	
</script>`
