### ISSUE TITLE
Bro pano pag gusto ko magdagdag ng Barangay? salamat paps!

### ISSUE THREAD

**Issue by jazzu20** [marvicrm/ph_provinces_and_cities#4]

**Comment by marvicrm** [comment]
@jazzu20 

Tol, medyo matrabaho pag idadagdag yung baranggay. pero possible naman,  Ganito sample code.

var cities = {
	'Laguna'  : [{
			'Calamba' : 'Baranggay 1',
			'Cabuyao' : 'Baranggay 2'
			}]
 }

// Print All Baranggay in Laguna
for( item in cities['Laguna'] ) {
  console.log(cities['Laguna'][item]);
}

// Print All Baranggay in Calamba
for( item in cities['Laguna'] ) {
  console.log( cities['Laguna'][item].Calamba );
}

**Comment by jazzu20** [comment]
Bro maraming salamat, di ko akalain magrereply ka :D Thanks!

may question lang ako kung paano gawin dynamic yung pag append ng option sa
baranggay

eto yung steps na nagawa ko na https://js.do/jazzu20/325876

Salamatsu!!

**Comment by marvicrm** [comment]
Eto tol, minodify ko ng konti yung code mo. paki-check na lang :)

https://js.do/marvicrm/325879

**Comment by jazzu20** [comment]
Nice nice.. mali pala yung approach ko

pero tol pag nag switch ako to a different province,  paano gawin empty
yung brgy option?

salamat paps.

**Comment by jazzu20** [comment]
ok na pala bro. salamat! ang lupit mo! hehe.
